<a href="https://colab.research.google.com/github/chetya17/ML-Lab-Codes/blob/main/ML%20Lab%207%20-%20SVM_for_digit_recognition.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import validation_curve
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import GridSearchCV
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.io import loadmat

In [ ]:
train_data = pd.read_csv('mnist_train.csv')

In [ ]:
test_data = pd.read_csv('mnist_test.csv')

In [ ]:
round(train_data.drop('label', axis=1).mean(), 2)


1x1      0.0
1x2      0.0
1x3      0.0
1x4      0.0
1x5      0.0
        ... 
28x24    0.0
28x25    0.0
28x26    0.0
28x27    0.0
28x28    0.0
Length: 784, dtype: float64

In [ ]:

y = train_data['label']
X = train_data.drop(columns = 'label') 
print(train_data.shape)

(5164, 785)


In [ ]:
X = X/255.0
test_data = test_data/255.0

print("X:", X.shape)
print("test_data:", test_data.shape)

X: (5164, 784)
test_data: (6333, 785)


In [ ]:
from sklearn.preprocessing import scale
X_scaled = scale(X)

# train test split
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size = 0.3, train_size = 0.2 ,random_state = 10)

In [ ]:
model_linear = SVC(kernel='linear')
model_linear.fit(X_train, y_train)

# predict
y_pred = model_linear.predict(X_test)

In [ ]:
from sklearn import metrics
from sklearn.metrics import confusion_matrix
# accuracy
print("accuracy:", metrics.accuracy_score(y_true=y_test, y_pred=y_pred), "\n")

# cm
print(metrics.confusion_matrix(y_true=y_test, y_pred=y_pred))

accuracy: 0.8935483870967742 

[[139   0   0   0   0   1   2   0   0   0]
 [  0 159   0   1   0   1   0   0   1   0]
 [  4   2 143   0   4   2   1   0   3   1]
 [  0   2   6 140   1   5   0   1   1   0]
 [  1   0   6   1 138   0   2   0   1   6]
 [  2   0   3   9   1 111   2   0   2   3]
 [  2   0   4   0   3   6 137   0   1   0]
 [  1   3   2   1   4   0   0 152   1   6]
 [  0   6   8   9   1   5   3   1 127   2]
 [  3   0   1   1   4   1   0   7   1 139]]


In [ ]:
non_linear_model = SVC(kernel='rbf')

# fit
non_linear_model.fit(X_train, y_train)

# predict
y_pred = non_linear_model.predict(X_test)

In [ ]:
print("accuracy:", metrics.accuracy_score(y_true=y_test, y_pred=y_pred), "\n")

# cm
print(metrics.confusion_matrix(y_true=y_test, y_pred=y_pred))

accuracy: 0.8754838709677419 

[[135   0   2   1   0   2   2   0   0   0]
 [  0 157   2   1   0   1   0   0   1   0]
 [  0   3 147   2   1   1   1   1   3   1]
 [  0   2  12 130   1   3   0   5   3   0]
 [  0   1  12   0 131   2   1   3   0   5]
 [  3   0   7   4   0 107   3   2   4   3]
 [  1   0  11   0   1   4 132   0   4   0]
 [  0   5   5   0   3   0   0 151   0   6]
 [  2   4   5   6   0   4   2   0 135   4]
 [  2   0   6   4   3   0   0  10   0 132]]


In [ ]:
folds = KFold(n_splits = 5, shuffle = True, random_state = 10)

# specify range of hyperparameters
# Set the parameters by cross-validation
hyper_params = [ {'gamma': [1e-2, 1e-3, 1e-4],
                     'C': [5,10]}]


# specify model
model = SVC(kernel="rbf")

# set up GridSearchCV()
model_cv = GridSearchCV(estimator = model, 
                        param_grid = hyper_params, 
                        scoring= 'accuracy', 
                        cv = folds, 
                        verbose = 1,
                        return_train_score=True)      

# fit the model
model_cv.fit(X_train, y_train)

Fitting 5 folds for each of 6 candidates, totalling 30 fits


GridSearchCV(cv=KFold(n_splits=5, random_state=10, shuffle=True),
             estimator=SVC(),
             param_grid=[{'C': [5, 10], 'gamma': [0.01, 0.001, 0.0001]}],
             return_train_score=True, scoring='accuracy', verbose=1)

In [ ]:
cv_results = pd.DataFrame(model_cv.cv_results_)
cv_results

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       0.404310      0.069920         0.124984        0.028455       5   
1       0.248710      0.037064         0.115753        0.029647       5   
2       0.187156      0.044747         0.095805        0.017144       5   
3       0.739167      0.500557         0.234008        0.176185      10   
4       0.636560      0.441518         0.255363        0.189111      10   
5       0.195290      0.069703         0.110706        0.043843      10   

  param_gamma                      params  split0_test_score  \
0        0.01     {'C': 5, 'gamma': 0.01}           0.768116   
1       0.001    {'C': 5, 'gamma': 0.001}           0.922705   
2      0.0001   {'C': 5, 'gamma': 0.0001}           0.908213   
3        0.01    {'C': 10, 'gamma': 0.01}           0.768116   
4       0.001   {'C': 10, 'gamma': 0.001}           0.917874   
5      0.0001  {'C': 10, 'gamma': 0.0001}           0.917874   

   split1_test_score  split2_test_score  ...  mean_test_score  std_test_score  \
0           0.661836           0.669903  ...         0.663660        0.066447   
1           0.869565           0.898058  ...         0.884668        0.024865   
2           0.898551           0.859223  ...         0.881741        0.018535   
3           0.661836           0.669903  ...         0.663660        0.066447   
4           0.869565           0.893204  ...         0.881760        0.022950   
5           0.893720           0.898058  ...         0.898241        0.010287   

   rank_test_score  split0_train_score  split1_train_score  \
0                5            1.000000            1.000000   
1                2            1.000000            1.000000   
2                4            0.943030            0.955152   
3                5            1.000000            1.000000   
4                3            1.000000            1.000000   
5                1            0.972121            0.974545   

   split2_train_score  split3_train_score  split4_train_score  \
0            1.000000            1.000000            1.000000   
1            1.000000            1.000000            0.998789   
2            0.945521            0.950363            0.949153   
3            1.000000            1.000000            1.000000   
4            1.000000            1.000000            1.000000   
5            0.973366            0.973366            0.969734   

   mean_train_score  std_train_score  
0          1.000000         0.000000  
1          0.999758         0.000484  
2          0.948644         0.004167  
3          1.000000         0.000000  
4          1.000000         0.000000  
5          0.972626         0.001637  

[6 rows x 22 columns]

In [ ]:
cv_results['param_C'] = cv_results['param_C'].astype('int')

# # plotting
plt.figure(figsize=(16,8))

# subplot 1/3
plt.subplot(131)
gamma_01 = cv_results[cv_results['param_gamma']==0.01]

plt.plot(gamma_01["param_C"], gamma_01["mean_test_score"])
plt.plot(gamma_01["param_C"], gamma_01["mean_train_score"])
plt.xlabel('C')
plt.ylabel('Accuracy')
plt.title("Gamma=0.01")
plt.ylim([0.60, 1])
plt.legend(['test accuracy', 'train accuracy'], loc='upper left')
plt.xscale('log')

# subplot 2/3
plt.subplot(132)
gamma_001 = cv_results[cv_results['param_gamma']==0.001]

plt.plot(gamma_001["param_C"], gamma_001["mean_test_score"])
plt.plot(gamma_001["param_C"], gamma_001["mean_train_score"])
plt.xlabel('C')
plt.ylabel('Accuracy')
plt.title("Gamma=0.001")
plt.ylim([0.60, 1])
plt.legend(['test accuracy', 'train accuracy'], loc='upper left')
plt.xscale('log')


# subplot 3/3
plt.subplot(133)
gamma_0001 = cv_results[cv_results['param_gamma']==0.0001]

plt.plot(gamma_0001["param_C"], gamma_0001["mean_test_score"])
plt.plot(gamma_0001["param_C"], gamma_0001["mean_train_score"])
plt.xlabel('C')
plt.ylabel('Accuracy')
plt.title("Gamma=0.0001")
plt.ylim([0.60, 1])
plt.legend(['test accuracy', 'train accuracy'], loc='upper left')
plt.xscale('log')


In [ ]:
best_score = model_cv.best_score_
best_hyperparams = model_cv.best_params_

print("The best test score is {0} corresponding to hyperparameters {1}".format(best_score, best_hyperparams))

The best test score is 0.8982411706767977 corresponding to hyperparameters {'C': 10, 'gamma': 0.0001}


In [ ]:
model = SVC(C=10, gamma=0.001, kernel="rbf")

model.fit(X_train, y_train)
y_pred = model.predict(X_test)

# metrics
print("accuracy", metrics.accuracy_score(y_test, y_pred), "\n")
print(metrics.confusion_matrix(y_test, y_pred), "\n")

accuracy 0.9025806451612903 

[[138   0   1   1   0   1   1   0   0   0]
 [  0 158   1   1   0   1   0   1   0   0]
 [  0   1 148   1   1   1   0   5   2   1]
 [  0   2   7 138   1   3   0   4   1   0]
 [  0   0   6   0 137   0   1   4   0   7]
 [  0   1   3   6   1 114   2   0   3   3]
 [  2   0   6   0   2   5 134   3   1   0]
 [  0   4   2   0   2   0   0 158   0   4]
 [  2   5   4   6   1   4   2   2 135   1]
 [  2   0   1   2   4   1   0   7   1 139]] 

